### ISSUE TITLE
Как добавить модификатор к имени рутового блока?

### ISSUE THREAD

**Issue by fliptheweb** [nikitabulatov/clssnms#1]
```js
const classNames = clssnms('wtf')
<div className={classNames({'--wtf-mod': true})}></div>
```

**Comment by fliptheweb** [comment]
А в каких случаях еще используется null в первом аргументе?
Может если передан null, то понятно что это именно этот блок? :)

**Comment by nikitabulatov** [comment]
🤔 Разумно

**Comment by nikitabulatov** [comment]
Хотя.. Возможно есть кейсы когда нужно рулить модификаторами без блока и элемента. Но я у нас по проекту погрепал, там таких кейсов нет. Спорно. Как ты считаешь @fliptheweb ?

**Comment by fliptheweb** [comment]
Ну если рили bem-convention, то такое невозможно по идее :)

**Comment by nikitabulatov** [comment]
Справедливо. Тогда вот тут будет сделано #2
